# Generated by Django 4.2 on 2026-05-28 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('promo_type', models.CharField(choices=[('PERCENT', 'Процентная скидка'), ('FIXED', 'Фиксированная скидка'), ('N_PLUS_1', 'N+1 (бесплатный товар)'), ('THRESHOLD', 'Пороговая скидка'), ('BUNDLE', 'Бандл')], max_length=50, verbose_name='Тип акции')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Размер скидки')),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Пороговая сумма')),
                ('n_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество N')),
                ('plus_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Бесплатных единиц')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('is_combinable', models.BooleanField(default=False, verbose_name='Совместима с другими акциями')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SCHEDULED', 'Запланирована'), ('ACTIVE', 'Активна'), ('PAUSED', 'Приостановлена'), ('COMPLETED', 'Завершена')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало действия')),
                ('end_datetime', models.DateTimeField(verbose_name='Конец действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Товар акции',
                'verbose_name_plural': 'Товары акции',
                'unique_together': {('promotion', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Категория акции',
                'verbose_name_plural': 'Категории акции',
                'unique_together': {('promotion', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PromotionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Время применения')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая цена')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма скидки')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Применение акции',
                'verbose_name_plural': 'Применения акций',
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, through='promotions.PromotionCategory', to='catalog.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, through='promotions.PromotionProduct', to='catalog.product', verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('ACTIVATE', 'Активация'), ('DEACTIVATE', 'Деактивация')], max_length=50, verbose_name='Действие')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('entity_id', models.IntegerField(verbose_name='ID объекта')),
                ('changed_fields', models.TextField(blank=True, verbose_name='Изменённые поля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotionapplication',
            index=models.Index(fields=['promotion', 'applied_at'], name='promotions__promoti_193b50_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status', 'start_datetime', 'end_datetime'], name='promotions__status_f8c22a_idx'),
        ),
    ]
